version: '3'
services:
  app:
    container_name: nestjsapp-app
    build: .
    ports:
      - "3333:3333"
    env_file: .env
    depends_on:
      - mongo
    tty: true
  mongo:
    container_name: nestjsapp-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
